"""Generates frameworks/<name>.md: one page per framework, control by control.

GENERATED. Do not edit by hand. CI regenerates these and fails if the result
differs from what is committed, which is the only way an index like this
stays true. A hand-maintained coverage table drifts on the first PR and then
claims coverage that no longer exists, which is the failure this repo is
about.

Each page opens with coverage at a glance per service, then lists every
control in the catalogue and the policies that cite it. A control nobody
covers says so instead of being missing from the table, because a table
that only shows what is covered reads as full coverage.
"""
import collections
import glob
import os
import re
import sys

import yaml

POLICIES = "policies/aws"
OUT = "frameworks"

CATALOGS = {
    "fsbp": ("catalogs/fsbp.txt", "AWS Foundational Security Best Practices",
             "FSBP", "service"),
    "pci-4.0": ("catalogs/pci-4.0.txt", "PCI DSS v4.0", "PCI", "requirement"),
    "cis-aws": ("catalogs/cis-aws.txt", "CIS AWS Foundations Benchmark",
                "CIS", "section"),
}

SEVERITY = {
    "critical": "🔴 critical",
    "high": "🟠 high",
    "medium": "🟡 medium",
    "low": "🔵 low",
    "info": "⚪ info",
}
ORDER = ["critical", "high", "medium", "low", "info"]

CITE = re.compile(r"^(FSBP|PCI|CIS|SOX)\s+(.+)$")


def read_catalog(path):
    controls, complete = [], None
    for line in open(path, encoding="utf-8"):
        line = line.strip()
        if line.startswith("#"):
            found = re.search(r"complete:\s*(yes|no)", line, re.I)
            if found:
                complete = found.group(1).lower() == "yes"
            continue
        if not line:
            continue
        parts = line.split(None, 1)
        controls.append(parts[1].strip() if len(parts) > 1 else line)
    return controls, complete


def read_policies():
    by_control = collections.defaultdict(list)
    for path in sorted(glob.glob(f"{POLICIES}/*.yml")):
        service = os.path.basename(path)
        for policy in yaml.safe_load(open(path))["policies"]:
            metadata = policy.get("metadata") or {}
            for cited in metadata.get("frameworks") or []:
                found = CITE.match(str(cited).strip())
                if found:
                    by_control[found.group(2).strip()].append(
                        (policy["name"], service, metadata.get("severity") or ""))
    return by_control


def bar(done, total, width=12):
    if not total:
        return ""
    filled = round(width * done / total)
    return "`" + "█" * filled + "░" * (width - filled) + "`"


def worst(severities):
    for level in ORDER:
        if level in severities:
            return SEVERITY[level]
    return ""


def page(catalog_path, title, prefix, grouping):
    controls, complete = read_catalog(catalog_path)
    by_control = read_policies()
    covered = [c for c in controls if by_control.get(c)]
    policies_here = {n for c in controls for n, _, _ in by_control.get(c, [])}

    # Group case-insensitively. AWS writes one FSBP control `Autoscaling.5`
    # with a lowercase s, alone among AutoScaling.1 through .10, and grouping
    # on the literal prefix would split the service in two and give both
    # halves the same anchor. The control IDs themselves stay verbatim: the
    # spelling is AWS's and normalising it is how you invent a control that
    # does not exist.
    buckets = collections.OrderedDict()
    for control in controls:
        buckets.setdefault(control.split(".")[0].lower(), []).append(control)
    grouped = collections.OrderedDict()
    for members in buckets.values():
        labels = [c.split(".")[0] for c in members]
        label = collections.Counter(labels).most_common(1)[0][0]
        grouped[label] = members

    out = [f"# {title}", ""]
    out.append("<!-- GENERATED by ci/generate_frameworks.py. Do not edit. -->")
    out.append("")

    if complete:
        pct = round(100 * len(covered) / len(controls)) if controls else 0
        out.append(f"### {bar(len(covered), len(controls), 24)} "
                   f"&nbsp; **{len(covered)} / {len(controls)}** controls "
                   f"&nbsp;·&nbsp; {pct}%")
        out.append("")
        out.append(f"{len(policies_here)} policies cover {len(covered)} of the "
                   f"{len(controls)} controls in this framework. The catalogue "
                   f"is complete, so the denominator is one you can check: "
                   f"[`{catalog_path}`]({'../' + catalog_path}).")
    else:
        out.append(f"### **{len(covered)}** controls covered "
                   f"&nbsp;·&nbsp; {len(policies_here)} policies")
        out.append("")
        out.append(f"No percentage. [`{catalog_path}`]({'../' + catalog_path}) "
                   f"holds a partial list of this framework, so any ratio "
                   f"against it would flatter whoever computed it. The count is "
                   f"real, the denominator is not.")
    out.append("")
    out.append("A control with no policy says `not covered`. That is a to-do, "
               "not something to leave out of the table. PRs welcome.")
    out.append("")

    out.append(f"## Coverage by {grouping}")
    out.append("")
    out.append(f"| {grouping.title()} | | Covered |")
    out.append("|:---|:---|---:|")
    for fam, block in grouped.items():
        hits = sum(1 for c in block if by_control.get(c))
        anchor = fam.lower().replace(".", "")
        out.append(f"| [**{fam}**](#{anchor}) | {bar(hits, len(block))} "
                   f"| {hits} / {len(block)} |")
    out.append("")
    out.append("---")
    out.append("")

    for fam, block in grouped.items():
        hits = sum(1 for c in block if by_control.get(c))
        out.append(f"## {fam}")
        out.append("")
        out.append(f"{bar(hits, len(block))} &nbsp; {hits} of {len(block)} covered")
        out.append("")
        out.append("| Control | Severity | Policies |")
        out.append("|:---|:---|:---|")
        for control in block:
            entries = by_control.get(control) or []
            if entries:
                names = "<br>".join(
                    f"[`{n}`](../{POLICIES}/{f})" for n, f, _ in entries)
                sev = worst({s for _, _, s in entries if s}) or "&nbsp;"
            else:
                names, sev = "`not covered`", "&nbsp;"
            out.append(f"| **{prefix} {control}** | {sev} | {names} |")
        out.append("")

    return "\n".join(out) + "\n"


def sox_page():
    """SOX has no numbered controls, it has ITGC domains. Counting domains as
    controls would be nonsense, so this page counts the other way: how many
    policies land in each domain."""
    by_domain = collections.defaultdict(list)
    for path in sorted(glob.glob(f"{POLICIES}/*.yml")):
        service = os.path.basename(path)
        for policy in yaml.safe_load(open(path))["policies"]:
            metadata = policy.get("metadata") or {}
            for cited in metadata.get("frameworks") or []:
                text = str(cited).strip()
                if text.startswith("SOX"):
                    domain = text.split(":", 1)[-1].strip() or "Unclassified"
                    by_domain[domain].append(
                        (policy["name"], service, metadata.get("severity") or ""))
    if not by_domain:
        return None

    total = sum(len(v) for v in by_domain.values())
    out = ["# SOX ITGC", ""]
    out.append("<!-- GENERATED by ci/generate_frameworks.py. Do not edit. -->")
    out.append("")
    out.append(f"### **{total}** policies &nbsp;·&nbsp; {len(by_domain)} ITGC domains")
    out.append("")
    out.append("SOX has no numbered control list to cross against. IT General "
               "Controls are domains, not checks, and every organisation maps "
               "its own controls into them. So there is no percentage here and "
               "there never will be: this page says which policies an auditor "
               "would file under which domain, and nothing more.")
    out.append("")
    for domain in sorted(by_domain):
        entries = sorted(by_domain[domain])
        out.append(f"## {domain}")
        out.append("")
        out.append(f"{len(entries)} policies")
        out.append("")
        out.append("| Policy | Severity | File |")
        out.append("|:---|:---|:---|")
        for name, service, severity in entries:
            sev = SEVERITY.get(severity, "&nbsp;")
            out.append(f"| [`{name}`](../{POLICIES}/{service}) | {sev} "
                       f"| `{service}` |")
        out.append("")
    return "\n".join(out) + "\n"


def _count_tests():
    """Counts test CASES, the number pytest prints, not test functions.

    A parametrised test is one `def` and several cases, so counting `def
    test_` under-reports. The badge sits next to a console block showing
    pytest's own output; two different numbers for the same thing is the
    small dishonesty this repo argues against.
    """
    total = 0
    for path in glob.glob("tests/aws/test_*.py"):
        src = open(path, encoding="utf-8").read()
        # Each @pytest.mark.parametrize decorator turns the def below it into
        # as many cases as it lists. Count the list entries, not the def.
        params = {}
        for block in re.finditer(
                r"@pytest\.mark\.parametrize\([^,]+,\s*\[(.*?)\]\s*\)\s*\ndef (test_\w+)",
                src, re.S):
            entries = [x for x in block.group(1).split("\n") if x.strip().rstrip(",")]
            params[block.group(2)] = max(1, len(entries))
        for name in re.findall(r"^def (test_\w+)", src, re.M):
            total += params.get(name, 1)
    return total


def badges():
    """Rewrites the badge block in README.md between its two markers.

    Static badges with numbers baked into a URL are a small lie waiting to
    happen: the count changes, the badge does not. So they get generated from
    the same data as everything else, and CI fails if the committed README
    disagrees with what this produces.
    """
    controls, _ = read_catalog(CATALOGS["fsbp"][0])
    by_control = read_policies()
    covered = sum(1 for c in controls if by_control.get(c))
    policies = sum(len(yaml.safe_load(open(f))["policies"])
                   for f in glob.glob(f"{POLICIES}/*.yml"))
    tests = _count_tests()

    repo = "gustavoortega/cloud-custodian-compliance-policies"
    row = " ".join([
        # The CI badge is the only one that is not a number this script
        # computed: it is GitHub reporting whether the workflow passed. It
        # goes first because a green coverage badge on a repo whose tests do
        # not run is exactly the kind of claim this repo argues against.
        f"[![ci](https://github.com/{repo}/actions/workflows/ci.yml/"
        f"badge.svg)](https://github.com/{repo}/actions/workflows/ci.yml)",
        f"![FSBP](https://img.shields.io/badge/FSBP-{covered}%2F{len(controls)}"
        f"_controls-2ea44f?style=flat-square)",
        f"![policies](https://img.shields.io/badge/policies-{policies}-"
        f"1f6feb?style=flat-square)",
        f"![tests](https://img.shields.io/badge/tests-{tests}_offline-"
        f"1f6feb?style=flat-square)",
        "![license](https://img.shields.io/badge/license-Apache_2.0-"
        "6e7781?style=flat-square)",
    ])
    body = f"<!-- badges -->\n{row}\n<!-- /badges -->"

    readme = open("README.md", encoding="utf-8").read()
    updated = re.sub(r"<!-- badges -->.*?<!-- /badges -->", body, readme,
                     flags=re.S)
    changed = updated != readme
    if changed:
        open("README.md", "w", encoding="utf-8").write(updated)
    return "README.md", changed


os.makedirs(OUT, exist_ok=True)
written = [badges()]

for key, (path, title, prefix, grouping) in CATALOGS.items():
    if not os.path.exists(path):
        continue
    target = f"{OUT}/{key}.md"
    body = page(path, title, prefix, grouping)
    changed = (not os.path.exists(target)
               or open(target, encoding="utf-8").read() != body)
    open(target, "w", encoding="utf-8").write(body)
    written.append((target, changed))

body = sox_page()
if body:
    target = f"{OUT}/sox-itgc.md"
    changed = (not os.path.exists(target)
               or open(target, encoding="utf-8").read() != body)
    open(target, "w", encoding="utf-8").write(body)
    written.append((target, changed))

for target, changed in written:
    print(f"{'regenerated' if changed else 'unchanged  '}  {target}")

drifted = [t for t, changed in written if changed]
if drifted and os.environ.get("CI"):
    print(f"\n{len(drifted)} generated page(s) were out of date. "
          f"Run ci/generate_frameworks.py and commit the result.")
    sys.exit(1)
