"""Generates frameworks/<name>.md: one page per framework, control by control.

GENERATED. Do not edit by hand. CI regenerates these and fails if the result
differs from what is committed, which is the only way an index like this
stays true. A hand-maintained coverage table drifts on the first PR and then
claims coverage that no longer exists, which is the failure this whole repo
is about.

Each page lists every control in the catalogue and the policies that cite
it, so a reader can answer "what covers FSBP RDS.3?" without opening 42
YAML files, and "what is not covered?" without doing arithmetic.
"""
import collections
import glob
import os
import re
import sys

import yaml

POLICIES = "policies/aws"
CATALOGS = {
    "fsbp": ("catalogs/fsbp.txt", "AWS Foundational Security Best Practices"),
    "pci-4.0": ("catalogs/pci-4.0.txt", "PCI DSS v4.0"),
    "cis-aws": ("catalogs/cis-aws.txt", "CIS AWS Foundations Benchmark"),
}
OUT = "frameworks"

CITE = re.compile(r"^(FSBP|PCI|CIS|SOX)\s+(.+)$")


def read_catalog(path):
    """Returns (controls, complete). `complete` is None when the file does not say."""
    controls, complete = [], None
    for line in open(path, encoding="utf-8"):
        line = line.strip()
        if line.startswith("#"):
            found = re.search(r"complete:\s*(yes|no)", line, re.I)
            if found:
                complete = found.group(1).lower() == "yes"
            continue
        if not line:
            continue
        parts = line.split(None, 1)
        controls.append(parts[1].strip() if len(parts) > 1 else line)
    return controls, complete


def read_policies():
    """control id -> [(policy name, file, severity)], for every cited control."""
    by_control = collections.defaultdict(list)
    for path in sorted(glob.glob(f"{POLICIES}/*.yml")):
        service = os.path.basename(path)
        for policy in yaml.safe_load(open(path))["policies"]:
            metadata = policy.get("metadata") or {}
            for cited in metadata.get("frameworks") or []:
                found = CITE.match(str(cited).strip())
                if found:
                    by_control[found.group(2).strip()].append(
                        (policy["name"], service, metadata.get("severity") or "")
                    )
    return by_control


def family(control):
    """`RDS.3` -> `RDS`, `1.2.1` -> `1`. Used only for grouping the tables."""
    return control.split(".")[0]


def page(key, catalog_path, title):
    controls, complete = read_catalog(catalog_path)
    by_control = read_policies()
    covered = [c for c in controls if by_control.get(c)]

    out = [f"# {title}", ""]
    out.append("<!-- GENERATED by ci/generate_frameworks.py. Do not edit. -->")
    out.append("")
    if complete:
        pct = round(100 * len(covered) / len(controls)) if controls else 0
        out.append(f"**{len(covered)} of {len(controls)} controls ({pct}%).** "
                   f"The catalogue is complete, so that percentage has a "
                   f"denominator you can check: `{catalog_path}`.")
    else:
        out.append(f"**{len(covered)} controls covered.** No percentage: "
                   f"`{catalog_path}` holds a partial list of this framework, "
                   f"so any ratio against it would flatter us. The count is "
                   f"real, the denominator is not.")
    out.append("")
    out.append("A control with no policy is not a bug report, it is a to-do. "
               "PRs welcome.")
    out.append("")

    grouped = collections.defaultdict(list)
    for control in controls:
        grouped[family(control)].append(control)

    for fam in sorted(grouped):
        block = grouped[fam]
        hits = sum(1 for c in block if by_control.get(c))
        out.append(f"## {fam} ({hits}/{len(block)})")
        out.append("")
        out.append("| Control | Policies | Severity |")
        out.append("|---|---|---|")
        for control in block:
            entries = by_control.get(control) or []
            if entries:
                names = "<br>".join(
                    f"[`{n}`](../{POLICIES}/{f})" for n, f, _ in entries)
                sev = ", ".join(sorted({s for _, _, s in entries if s})) or "-"
            else:
                names, sev = "_not covered_", "-"
            out.append(f"| `{control}` | {names} | {sev} |")
        out.append("")

    return "\n".join(out) + "\n"


os.makedirs(OUT, exist_ok=True)
written = []
for key, (path, title) in CATALOGS.items():
    if not os.path.exists(path):
        continue
    target = f"{OUT}/{key}.md"
    body = page(key, path, title)
    stale = os.path.exists(target) and open(target, encoding="utf-8").read() != body
    missing = not os.path.exists(target)
    with open(target, "w", encoding="utf-8") as fh:
        fh.write(body)
    written.append((target, stale or missing))

drifted = [t for t, changed in written if changed]
for target, changed in written:
    print(f"{'regenerated' if changed else 'unchanged  '}  {target}")

if drifted and os.environ.get("CI"):
    print(f"\n{len(drifted)} generated page(s) were out of date. "
          f"Run ci/generate_frameworks.py and commit the result.")
    sys.exit(1)
